<a href="https://colab.research.google.com/github/zs10011598/tmII-2022-II/blob/main/ayudantia_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # Importar Numpy

Creacion de Array

In [3]:
a = np.array([1, 2, 3]) # Creacion de un array de dimension 1 (3)

a

array([1, 2, 3])

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Creacion de array de dimension 2 (3, 3)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]) # Creacion de un array de dimension 3 (3, 2, 3)

c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

Funciones para definir arrays predefinidas en Numpy

In [11]:
np.zeros((3, 4, 2)) # Craecion de array cuyas entradas son 0s

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.ones( (2, 3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.arange(5, 30, 5) # Array de dimension 1 con punto inicial y un paso especificado

array([ 5, 10, 15, 20, 25])

In [16]:
np.linspace(0, 20, 10) # Array de dimension 1 con punto inicial y final con una muestra especificada

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.full((2, 3), 7) # Array constante

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np.eye(4) # Array de dimension 2 identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.random((3, 2)) # Array con entradas aleatorias entra 0 y 1

array([[0.60027556, 0.7558488 ],
       [0.00585994, 0.40809768],
       [0.86519665, 0.10747252]])

Propiedades de los Arrays

In [22]:
c.shape # Tamano de las dimensiones

(3, 2, 3)

In [23]:
c.ndim # Numero de dimensiones

3

In [24]:
b.size # Numero de entradas

9

In [25]:
a.dtype

dtype('int64')

Tipos de datos

In [26]:
d = np.array([1, 2, 3], dtype=np.int64)

d.dtype

dtype('int64')

In [27]:
d = np.array([1, 2, 3], dtype=np.float32)

d.dtype

dtype('float32')

In [28]:
d

array([1., 2., 3.], dtype=float32)

np.complex - Numeros complejos <br>
np.bool - Booleanos <br>
np.objects - Objetos <br>
np.string_ - Cadenas 

## Operaciones matematicas

In [29]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
b + d # Suma

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
np.add(b, d) # Suma

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
a + b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## Broadcasting

La manera en la que Numpy trata a los arreglos de diferentes dimensiones para las operaciones matematicas. 

In [33]:
np.array([[1, 2, 3], [4, 5, 6]]) + np.array([[2, 2], [2, 2]])

ValueError: ignored

Para determinar si se puede hacer broadcasting entre dos arreglos, checamos las dimensiones de derecha a izquierda y debe de cumplirse lo siguiente:

1. las dimensiones sean de la misma longitud o
2. Que alguna de las dimensiones sea 1

In [34]:
# Se puede
#     3
# 3 X 3

# 15 X 4 X 1 X 3 X 10
#      4 X 9 X 1 X 10

# No se puede
# 2 x 3
# 2 x 2

# 10 X 7 X 9 X 5
#      5 X 1 X 5

In [35]:
b - d # Sustraccion

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.subtract(b, d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
b * d # Multiplicacion entrada por entrada

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
np.multiply(b, d)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
b/d # Division entrada por entrada

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.divide(b, d)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.exp(a) # Aplica exponencial a cada entrada

array([ 2.71828183,  7.3890561 , 20.08553692])

In [42]:
np.sqrt(a) # Aplica la raiz cuadrada a cada entrada

array([1.        , 1.41421356, 1.73205081])

np.sin() - Aplica el seno a cada entrada <br>
np.cos() - Aplica el coseno a cada entrada <br>
np.log() - Aplica el logaritmo natural a cada entrada <br>

In [43]:
b.dot(d)  # Multiplicacion de matrices

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [44]:
e = np.array([[1, 2], [1, 2]])
f = np.eye(2)

e.dot(f)

array([[1., 2.],
       [1., 2.]])

Comparar Arrays

In [46]:
g = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

g

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [47]:
g == b # Igualdad elemento por elemento

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [48]:
b == d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
b < g

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [50]:
np.array_equal(b, g) # Compara si todas las entradas son iguales

False

In [51]:
np.array_equal(d, b)

True

Funciones agregadas

In [55]:
a

array([1, 2, 3])

In [52]:
a.sum() # Suma todas las entradas del array

6

In [53]:
a.min() # Minimo de las entradas elarray

1

In [54]:
a.max() # Maximo de las entradas del array

3

In [57]:
a.mean() # Media de las entradas

2.0

In [58]:
np.median(a) # Mediana  de las entradas

2.0

In [60]:
np.std(a) # Desviacion estandar

0.816496580927726

In [62]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
b.cumsum(axis=0) # Suma acumulativa a lo largo del eje especificado (0 - filas, 1 - columnas)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [63]:
b.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

## Slicing, Indexing

In [67]:
a[2] # Acceso a entradas

3

In [66]:
b[2, 2]

9

In [68]:
a[0:2] # Cortar arrays

array([1, 2])

In [70]:
b[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [71]:
b[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [73]:
a[a == 2]

array([2])